### ISSUE TITLE
Testing with non-primitive datatypes as output

### ISSUE THREAD

**Issue by LoyVanBeek** [team-vigir/flexbe_behavior_engine#91]
My goal, for starters, is to write a simple test for a state that puts a `PoseStamped` in the userdata output. 
I can't figure out how to represent a PoseStamped, or even a list thereof, in a .test file.

- [ ] Representing as yaml, eg. copy-paste the output of the failed test into the testcase: :negative_squared_cross_mark:
- [ ] Encoding as a string: :negative_squared_cross_mark:
- [ ] Represent as dictionary: :negative_squared_cross_mark:
- [x] Put the yaml-encoded objects in the .test yaml-file, as for example in https://github.com/mojin-robotics/flexbe_behavior_engine/blob/80099959dd62bead15e145f464e9d6e390f200ba/flexbe_states/tests/subscriber_state_pose.test

The equals-check is made in https://github.com/team-vigir/flexbe_behavior_engine/blob/master/flexbe_testing/src/flexbe_testing/state_tester.py#L184 

I've been looking for other states that output a PoseStamped and have tests, but they do not test the output, eg. https://github.com/CNURobotics/flexible_navigation/blob/kinetic_devel/flex_nav_flexbe_states/tests/get_pose_state.test

**Comment by LoyVanBeek** [comment]
While going through the source of FlexBE, I stumbled on a [`.test`-file](https://github.com/mojin-robotics/flexbe_behavior_engine/blob/80099959dd62bead15e145f464e9d6e390f200ba/flexbe_states/tests/subscriber_state_pose.test) that did almost what I wanted, using an approach that failed earlier because I got the formatting wrong I think: dump to yaml.

To get the expected data, I just instantiate the PoseStamped I want and throw it into yaml dumper:
```python
from geometry_msgs.msg import PoseStamped
import yaml
p = PoseStamped()
p2 = PoseStamped()
p2.header.frame_id = "base_footprint"
print yaml.dump([p, p2])
```
Outputting 
```yaml
- !!python/object/new:geometry_msgs.msg._PoseStamped.PoseStamped
  state:
  - !!python/object/new:std_msgs.msg._Header.Header
    state:
    - 0
    - !!python/object/new:genpy.rostime.Time
      state: [0, 0]
    - ''
  - !!python/object/new:geometry_msgs.msg._Pose.Pose
    state:
    - !!python/object/new:geometry_msgs.msg._Point.Point
      state: [0.0, 0.0, 0.0]
    - !!python/object/new:geometry_msgs.msg._Quaternion.Quaternion
      state: [0.0, 0.0, 0.0, 0.0]
- !!python/object/new:geometry_msgs.msg._PoseStamped.PoseStamped
  state:
  - !!python/object/new:std_msgs.msg._Header.Header
    state:
    - 0
    - !!python/object/new:genpy.rostime.Time
      state: [0, 0]
    - base_footprint
  - !!python/object/new:geometry_msgs.msg._Pose.Pose
    state:
    - !!python/object/new:geometry_msgs.msg._Point.Point
      state: [0.0, 0.0, 0.0]
    - !!python/object/new:geometry_msgs.msg._Quaternion.Quaternion
      state: [0.0, 0.0, 0.0, 0.0]

```

which you can copy-paste into the .test file, but take care to get the right indentation of course.
